from pptx import Presentation
from pptx.util import Inches

def generate_ppt(title, slide_contents):
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]

    # Title Slide
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by AI Task Automator"

    # Content Slides
    for i, content in enumerate(slide_contents):
        slide_layout = prs.slide_layouts[1]  # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = f"Slide {i+1}"
        slide.placeholders[1].text = content

    prs.save(f"{title}.pptx")
